version: "3.9"

services:
  # Backend API server
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always

  # RQ worker for background jobs
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music-worker
    command: python worker.py
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - backend
    restart: always
